# numpy Eamples
https://www.youtube.com/watch?v=vh525RjO6C0&list=PLZoTAELRMXVPBTrWtJkn3wWQxZkmTXGwe&index=7&ab_channel=KrishNaik

**array (row index, column index)**

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6], [9,7,6,8,9]
               ])

In [56]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

arr [row: column]

arr[from which row index (: to) which excluding index, from which column index (: to) which excluding index]

arr[ from : till : steps]

In [60]:
arr[::2, ::2]

array([[1, 3, 5],
       [9, 6, 9]])

In [24]:
arr[:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [54]:
arr[1:2,-2:]

array([[5, 6]])

In [55]:
arr[1:2,3:]

array([[5, 6]])

In [13]:
arr[:2,:2]

array([[1, 2],
       [2, 3]])

In [11]:
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [19]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [21]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,10, step=2)

array([0, 2, 4, 6, 8])

In [69]:
arr = np.random.randint(1,25,25).reshape(5,5)
arr

array([[14,  9, 18,  8,  2],
       [16, 13, 17,  8, 18],
       [15, 10, 11,  3, 18],
       [15, 21,  7, 16,  9],
       [10, 12,  2, 18,  4]])

In [70]:
Index_arr = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
Index_arr # Elements at indices (1, 3), (1, 2), (0, 1), (3, 0)

array([ 8, 17,  9, 15])

# normal range v/s arange

In [26]:
[i for i in range(1,5)]

[1, 2, 3, 4]

In [34]:
[i for i in range(.1,2.5)]

TypeError: 'float' object cannot be interpreted as an integer

In [36]:
np.arange(.1, 5.5, step = 2)

array([0.1, 2.1, 4.1])

# linspace

In [63]:
np.linspace(1,5,10) # return 10 numbers b/w 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# copy function & broadcasting

In [43]:
a = np.array([1,2,3,4,5,6])

In [45]:
a[1:3] = 100

In [46]:
a

array([  1, 100, 100,   4,   5,   6])

# copy

In [48]:
b = a.copy()
b[1:2] = 2000
b

array([   1, 2000,  100,    4,    5,    6])

# Reshape (depends on number of items)

In [74]:
a = np.arange(1,16) # 15 items
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
# 3 rows and 5 columns : (3x5) = 15
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [76]:
# 1 rows and 15 columns : (1x15) = 15
a.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

# generate one's

In [86]:
np.ones(5)  # default type is float

array([1., 1., 1., 1., 1.])

In [87]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# generate zero's

In [88]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [89]:
np.zeros((3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# random distribution

In [99]:
np.random.rand(3,5)  # any random numbers b/w 3x5 matrix

array([[0.25490244, 0.90792975, 0.84957788, 0.76719216, 0.19141715],
       [0.17133848, 0.78342457, 0.61850833, 0.31305729, 0.21782328],
       [0.02218564, 0.39324981, 0.45699604, 0.83651195, 0.16046005]])

In [61]:
np.random.randint(3,10) # any random number

array([4, 7])

In [107]:
np.random.randint(3,10,6) # any 6 random number b/w 3 to 10

array([5, 4, 5, 9, 7, 6])

In [106]:
np.random.randint(3,10,6).reshape(3,2)

array([[8, 5],
       [5, 8],
       [3, 5]])

In [112]:
np.random.randn(3,5)

array([[ 0.97240046, -0.00870121, -0.65795682,  2.06224602, -0.32086253],
       [-0.28067047, -1.09918734,  1.89486987,  0.06014157,  1.43366376],
       [-1.96113443, -0.11504037, -0.91408948, -0.80776289, -1.57427929]])

In [71]:
arr

array([[14,  9, 18,  8,  2],
       [16, 13, 17,  8, 18],
       [15, 10, 11,  3, 18],
       [15, 21,  7, 16,  9],
       [10, 12,  2, 18,  4]])

In [97]:
a = arr.reshape(1,-1)
a.shape, a

((1, 25),
 array([[14,  9, 18,  8,  2, 16, 13, 17,  8, 18, 15, 10, 11,  3, 18, 15,
         21,  7, 16,  9, 10, 12,  2, 18,  4]]))

In [98]:
a = arr.reshape(-1,1)
a.shape, a

((25, 1),
 array([[14],
        [ 9],
        [18],
        [ 8],
        [ 2],
        [16],
        [13],
        [17],
        [ 8],
        [18],
        [15],
        [10],
        [11],
        [ 3],
        [18],
        [15],
        [21],
        [ 7],
        [16],
        [ 9],
        [10],
        [12],
        [ 2],
        [18],
        [ 4]]))

In [102]:
# First Array
arr1 = np.array([[4, 7], 
                 [2, 9]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6],
                 [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 17.]]


In [103]:
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)


Addition of Array elements: 
22.0


In [104]:
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)


Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 3.        ]]


In [105]:
# Transpose of Array
# using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)


Transpose of Array: 
[[4. 2.]
 [7. 9.]]


In [106]:
np.multiply(arr1,arr2)

array([[12., 42.],
       [ 4., 72.]])

In [107]:
matrix=[[1,2,3],[4,5,6]]

In [108]:
matrix

[[1, 2, 3], [4, 5, 6]]

In [110]:
np.transpose(matrix)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [148]:
w = np.ones((3,3), dtype=int)
w

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [149]:
w[::2,::2] = 0
w[1::2,1::2] = 0 
w

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

## Differences between Flatten() and Ravel() Numpy Functions

In [178]:
a = np.array( [ (1,7,3,4),(3,2,4,1) ] )
a

array([[1, 7, 3, 4],
       [3, 2, 4, 1]])

In [151]:
f = a.flatten()
f

array([1, 7, 3, 4, 3, 2, 4, 1])

In [179]:
r = a.ravel()
r

array([1, 7, 3, 4, 3, 2, 4, 1])

In [163]:
a[1:,2:3]

array([[4]])

In [183]:
a[1:,2:3] = 0

In [166]:
a

array([[1, 7, 3, 4],
       [3, 2, 0, 1]])

In [167]:
r

array([1, 7, 3, 4, 3, 2, 4, 1])

In [168]:
f

array([1, 7, 3, 4, 3, 2, 4, 1])

In [180]:
r[0]=1000

In [184]:
r

array([1000,    7,    3,    4,    3,    2,    0,    1])

In [185]:
a

array([[1000,    7,    3,    4],
       [   3,    2,    0,    1]])

In [177]:
a = np.array([(1,2,3,4),(3,1,4,2)]) 
b = a.ravel() 
b[0]=1000
print(b) 
print(a)

[1000    2    3    4    3    1    4    2]
[[1000    2    3    4]
 [   3    1    4    2]]


In [187]:
np.full((3, 3), 6, dtype = int)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [188]:
arr

array([[14,  9, 18,  8,  2],
       [16, 13, 17,  8, 18],
       [15, 10, 11,  3, 18],
       [15, 21,  7, 16,  9],
       [10, 12,  2, 18,  4]])

In [191]:
arr[arr > 15]

array([18, 16, 17, 18, 18, 21, 16, 18])

In [192]:
arr.T

array([[14, 16, 15, 15, 10],
       [ 9, 13, 10, 21, 12],
       [18, 17, 11,  7,  2],
       [ 8,  8,  3, 16, 18],
       [ 2, 18, 18,  9,  4]])