In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
## Vocabulary size
voc_size = 10000

In [6]:
# one hot representation
onehot_repr = [one_hot(words, voc_size) for words in sent ]
print(onehot_repr)

[[9729, 9346, 6696, 4084], [9729, 9346, 6696, 6094], [9729, 9430, 6696, 1260], [231, 2208, 5556, 293, 4978], [231, 2208, 5556, 293, 1335], [6004, 9729, 5770, 6696, 9712], [2238, 3597, 7513, 293]]


# Word Embedding Representation 

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length) 
print(embedded_docs)

[[   0    0    0    0 9729 9346 6696 4084]
 [   0    0    0    0 9729 9346 6696 6094]
 [   0    0    0    0 9729 9430 6696 1260]
 [   0    0    0  231 2208 5556  293 4978]
 [   0    0    0  231 2208 5556  293 1335]
 [   0    0    0 6004 9729 5770 6696 9712]
 [   0    0    0    0 2238 3597 7513  293]]


In [10]:
dim = 15

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 15)             150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[-4.11041491e-02 -4.74535711e-02  4.10879739e-02 -4.58311215e-02
   -2.88018938e-02  4.87122200e-02  1.42190121e-02  2.45626234e-02
    1.76850446e-02 -4.85266447e-02  1.28863342e-02 -3.37793976e-02
    1.63674392e-02 -3.43862921e-03  5.68526983e-03]
  [-4.11041491e-02 -4.74535711e-02  4.10879739e-02 -4.58311215e-02
   -2.88018938e-02  4.87122200e-02  1.42190121e-02  2.45626234e-02
    1.76850446e-02 -4.85266447e-02  1.28863342e-02 -3.37793976e-02
    1.63674392e-02 -3.43862921e-03  5.68526983e-03]
  [-4.11041491e-02 -4.74535711e-02  4.10879739e-02 -4.58311215e-02
   -2.88018938e-02  4.87122200e-02  1.42190121e-02  2.45626234e-02
    1.76850446e-02 -4.85266447e-02  1.28863342e-02 -3.37793976e-02
    1.63674392e-02 -3.43862921e-03  5.68526983e-03]
  [-4.11041491e-02 -4.74535711e-02  4.10879739e-02 -4.58311215e-02
   -2.88018938e-02  4.87122200e-02  1.42190121e-02  2.45626234e-02
    1.76850446e-02 -4.85266447e-02  1.28863342e-02 -3.37793976e-02
    1.63674392e-02 -3.43862921e-03  5.68

In [16]:
print(model.predict(embedded_docs)[0])

[[-4.1104149e-02 -4.7453571e-02  4.1087974e-02 -4.5831122e-02
  -2.8801894e-02  4.8712220e-02  1.4219012e-02  2.4562623e-02
   1.7685045e-02 -4.8526645e-02  1.2886334e-02 -3.3779398e-02
   1.6367439e-02 -3.4386292e-03  5.6852698e-03]
 [-4.1104149e-02 -4.7453571e-02  4.1087974e-02 -4.5831122e-02
  -2.8801894e-02  4.8712220e-02  1.4219012e-02  2.4562623e-02
   1.7685045e-02 -4.8526645e-02  1.2886334e-02 -3.3779398e-02
   1.6367439e-02 -3.4386292e-03  5.6852698e-03]
 [-4.1104149e-02 -4.7453571e-02  4.1087974e-02 -4.5831122e-02
  -2.8801894e-02  4.8712220e-02  1.4219012e-02  2.4562623e-02
   1.7685045e-02 -4.8526645e-02  1.2886334e-02 -3.3779398e-02
   1.6367439e-02 -3.4386292e-03  5.6852698e-03]
 [-4.1104149e-02 -4.7453571e-02  4.1087974e-02 -4.5831122e-02
  -2.8801894e-02  4.8712220e-02  1.4219012e-02  2.4562623e-02
   1.7685045e-02 -4.8526645e-02  1.2886334e-02 -3.3779398e-02
   1.6367439e-02 -3.4386292e-03  5.6852698e-03]
 [-1.6458176e-02  1.2285374e-02 -2.3913467e-02  4.9638081e-02
  