# numpy Eamples
https://www.youtube.com/watch?v=vh525RjO6C0&list=PLZoTAELRMXVPBTrWtJkn3wWQxZkmTXGwe&index=7&ab_channel=KrishNaik

**array (row index, column index)**

In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6], [9,7,6,8,9]
               ])

In [5]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
arr[:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr[:2,:2]

array([[1, 2],
       [2, 3]])

In [11]:
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [19]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [21]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,10, step=2)

array([0, 2, 4, 6, 8])

# normal range v/s arange

In [26]:
[i for i in range(1,5)]

[1, 2, 3, 4]

In [34]:
[i for i in range(.1,2.5)]

TypeError: 'float' object cannot be interpreted as an integer

In [36]:
np.arange(.1, 5.5, step = 2)

array([0.1, 2.1, 4.1])

# linspace

In [37]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# copy function & broadcasting

In [43]:
a = np.array([1,2,3,4,5,6])

In [45]:
a[1:3] = 100

In [46]:
a

array([  1, 100, 100,   4,   5,   6])

# copy

In [48]:
b = a.copy()
b[1:2] = 2000
b

array([   1, 2000,  100,    4,    5,    6])

# Reshape (depends on number of items)

In [74]:
a = np.arange(1,16) # 15 items
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
# 3 rows and 5 columns : (3x5) = 15
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [76]:
# 1 rows and 15 columns : (1x15) = 15
a.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

# generate one's

In [86]:
np.ones(5)  # default type is float

array([1., 1., 1., 1., 1.])

In [87]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# generate zero's

In [88]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [89]:
np.zeros((3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# random distribution

In [99]:
np.random.rand(3,5)  # any random numbers b/w 3x5 matrix

array([[0.25490244, 0.90792975, 0.84957788, 0.76719216, 0.19141715],
       [0.17133848, 0.78342457, 0.61850833, 0.31305729, 0.21782328],
       [0.02218564, 0.39324981, 0.45699604, 0.83651195, 0.16046005]])

In [98]:
np.random.randint(3,10) # any random number

9

In [107]:
np.random.randint(3,10,6)

array([5, 4, 5, 9, 7, 6])

In [106]:
np.random.randint(3,10,6).reshape(3,2)

array([[8, 5],
       [5, 8],
       [3, 5]])

In [112]:
np.random.randn(3,5)

array([[ 0.97240046, -0.00870121, -0.65795682,  2.06224602, -0.32086253],
       [-0.28067047, -1.09918734,  1.89486987,  0.06014157,  1.43366376],
       [-1.96113443, -0.11504037, -0.91408948, -0.80776289, -1.57427929]])