# *params and key arguments **arg 

In [183]:
def doSomething1(name, mobile='no mobile'):
    print(name, mobile)
    print(type(name), type(mobile))

In [184]:
doSomething1('n')
doSomething1('n', 'g')

n no mobile
<class 'str'> <class 'str'>
n g
<class 'str'> <class 'str'>


In [185]:
def doSomething(mobile, *items, **dic):
    print(mobile, items, dic)
    print(type(items), type(dic))

In [9]:
doSomething('123', 'n', 'g', add1='line1', add2='line2')

123 ('n', 'g') {'add1': 'line1', 'add2': 'line2'}
<class 'tuple'> <class 'dict'>


In [11]:
doSomething('123', 'n', 'g', {'add1':'line1', 'add2':'line2'})

123 ('n', 'g', {'add1': 'line1', 'add2': 'line2'}) {}
<class 'tuple'> <class 'dict'>


In [12]:
doSomething('123', 'n', 'g', **{'add1':'line1', 'add2':'line2'})

123 ('n', 'g') {'add1': 'line1', 'add2': 'line2'}
<class 'tuple'> <class 'dict'>


In [13]:
doSomething('123', *['n', 'g'], **{'add1':'line1', 'add2':'line2'})

123 ('n', 'g') {'add1': 'line1', 'add2': 'line2'}
<class 'tuple'> <class 'dict'>


In [14]:
doSomething('123', *['n', 'g'], {'add1':'line1', 'add2':'line2'})

123 ('n', 'g', {'add1': 'line1', 'add2': 'line2'}) {}
<class 'tuple'> <class 'dict'>


# list comprehension

In [156]:
ll = [ i for i in range(0,10)];
type(ll)

list

In [158]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [186]:
def get_even(lst):
    for i in lst:
        if i % 2 == 0:
            yield i

In [160]:
def get_even2(lst):
    ev = []
    for i in lst:
        if i % 2 == 0:
            ev.append(i)
    return ev

In [161]:
get_even2(ll)

[0, 2, 4, 6, 8]

In [162]:
list(get_even(ll))

[0, 2, 4, 6, 8]

In [169]:
[ i%2==0 for i in ll]

[True, False, True, False, True, False, True, False, True, False]

## Keep if on the left side, when else part is required

In [190]:
[i if i%2==0 else None for i in ll]

[0, None, 2, None, 4, None, 6, None, 8, None]

## Keep if on the right side, when else part is not required

In [189]:
[i for i in ll if i%2==0 ]

[0, 2, 4, 6, 8]

## labmda with if condition

In [193]:
func = lambda x : 'even' if x % 2 == 0 else 'odd'

In [194]:
func(43), func(44)

('odd', 'even')

# map() Function
map(function, iterable(s))

process the items and then return accordingly

In [205]:
# Without using lambdas
def starts_with_A(s):
    return s[0] == "A"

fruit = ["Apple", "Banana", "Pear", "Apricot", "Orange"]
map_object = map(starts_with_A, fruit)
print(type(map_object))
print(list(map_object))

<class 'filter'>
['Apple', 'Apricot']


In [201]:
result = map(lambda x : x %2==0, ll)
list(result)

[True, False, True, False, True, False, True, False, True, False]

In [202]:
result = map(lambda x: func(x), ll)
list(result)

['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

In [203]:
result = map(lambda x : 'even' if x % 2 == 0 else 'odd', ll)
list(result)

['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

## filter() Function
filter(function, iterable(s))

return the filtered items

In [204]:
# Without using lambdas
def starts_with_A(s):
    return s[0] == "A"

fruit = ["Apple", "Banana", "Pear", "Apricot", "Orange"]
filter_object = filter(starts_with_A, fruit)

print(list(filter_object))

['Apple', 'Apricot']


In [206]:
result = filter(lambda x : x %2==0, ll)
list(result)

[0, 2, 4, 6, 8]

## reduce() Function
reduce(function, [sequence], initial)

In [209]:
from functools import reduce

def add(x, y): return x + y

list = [1,2,3,4,6]
print(reduce(add, list))

16


In [211]:
print(reduce(lambda a,b : a+b, list, 10))

26


In [213]:
name = 'n'
last = 'f'
print(f'first {name} and last {last}')

first n and last f


In [214]:
ll

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [223]:
items = iter(ll)
items

In [224]:
next(items)

0

In [225]:
next(items)

1

In [226]:
next(items)

2

In [228]:
for i in items:
    print(i)

3
4
5
6
7
8
9


# Decimal to binary
```
0: 0000
1: 0001
2: 0010
3: 0011
4: 0100
5: 0101
6: 0110
7: 0111
8: 1000
9: 1001
```

```
2|7|1
-----
2|3|1
-----
|1|


7 = 0111
```

# Binary to decimal
```
sum = d(2)^3 + d(2)^2 + d(2)^1 + d(2)^0
    = 0(2)^3 + 1(2)^2 + 1(2)^1 + 1(2)^0
    = 0 + 4 + 2 + 1
    = 7
```

In [45]:
def getBinary(n):
    return bin(n).replace("0b", "")
getBinary(9)

'1001'

## Zip

In [1]:
a = [1, 2]
b = [3, 4]
c = [5, 6]

In [6]:
f = zip(a,b,c)

In [7]:
list(f)

[(1, 3, 5), (2, 4, 6)]

In [8]:
a = [1,2,3,]
a

[1, 2, 3]

## reverse list

In [16]:
a[::-1]

[3, 2, 1]

# Generate randome numbers

In [2]:
import random

In [8]:
# Any random number
random.random()

0.9468805187427284

In [36]:
# Any random number b/w 3 to 6
for i in range(1, 10):
    print(random.randint(3, 6), end=", ")
print('\n')
print([random.randint(1, 100) for i in range(1,10)])

5, 5, 4, 6, 6, 3, 4, 4, 4, 

[87, 18, 97, 16, 52, 29, 8, 74, 92]


In [40]:
# Any 3 random numbers from the given list
print(random.sample([1,2,3,4,5], 3))
print(random.sample(range(1,5), 3))

[5, 2, 1]
[1, 3, 2]


In [42]:
[random.randrange(1, 50, 1) for i in range(1,5)]

[37, 44, 25, 16]

In [53]:
random.randrange(1, 50, 13)

40

In [55]:
import numpy as np
 
# generates list of 4 float values
print(np.random.random_sample(size = 4))

[0.92055301 0.69191877 0.66269422 0.72135318]


In [56]:
# generates 2d list of 4*4
print(np.random.random_sample(size = (4,4)))

[[0.71632563 0.72494245 0.59623881 0.58621877]
 [0.75483062 0.96982739 0.88614986 0.36982769]
 [0.22104223 0.8621214  0.33903601 0.15140657]
 [0.64492262 0.83216504 0.90543986 0.47695431]]


In [57]:
# print the list of 10 integers from 3  to 7 
print(list(np.random.randint(low = 3,high=8,size=10)))

[7, 4, 7, 5, 4, 6, 4, 5, 7, 6]


In [58]:
# print the list of 5 integers from 0 to 2
# if high parameter is not passed during 
# function call then results are from [0, low)
print(list(np.random.randint(low = 3,size=5)))

[2, 1, 2, 0, 2]
