In [41]:
import pandas as pd

In [42]:
dataset = pd.read_csv('car+data.csv')

In [43]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   door      1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [44]:
dataset.head()

buying  maint door persons lug_boot safety  class
0  vhigh  vhigh    2       2    small    low  unacc
1  vhigh  vhigh    2       2    small    med  unacc
2  vhigh  vhigh    2       2    small   high  unacc
3  vhigh  vhigh    2       2      med    low  unacc
4  vhigh  vhigh    2       2      med    med  unacc

In [45]:
dataset.isnull()

buying  maint   door  persons  lug_boot  safety  class
0      False  False  False    False     False   False  False
1      False  False  False    False     False   False  False
2      False  False  False    False     False   False  False
3      False  False  False    False     False   False  False
4      False  False  False    False     False   False  False
...      ...    ...    ...      ...       ...     ...    ...
1723   False  False  False    False     False   False  False
1724   False  False  False    False     False   False  False
1725   False  False  False    False     False   False  False
1726   False  False  False    False     False   False  False
1727   False  False  False    False     False   False  False

[1728 rows x 7 columns]

# Column Label encoding

In [46]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [47]:
dataset['buying'].value_counts()

low      432
vhigh    432
med      432
high     432
Name: buying, dtype: int64

In [48]:
label_encoder = preprocessing.LabelEncoder()
dataset['buying_original_df'] = dataset[['buying']].copy()
dataset['buying']= label_encoder.fit_transform(dataset['buying']) 
# dataset = pd.concat([dataset, buying_original_df])
dataset['buying'].value_counts()

3    432
2    432
1    432
0    432
Name: buying, dtype: int64

In [66]:
dataset[['buying_original_df' , 'buying']]

buying_original_df  buying
0                 vhigh       3
1                 vhigh       3
2                 vhigh       3
3                 vhigh       3
4                 vhigh       3
...                 ...     ...
1723                low       1
1724                low       1
1725                low       1
1726                low       1
1727                low       1

[1728 rows x 2 columns]

In [10]:
dataset['maint']= label_encoder.fit_transform(dataset['maint']) 
dataset['door']= label_encoder.fit_transform(dataset['door']) 
dataset['persons']= label_encoder.fit_transform(dataset['persons']) 
dataset['lug_boot']= label_encoder.fit_transform(dataset['lug_boot']) 
dataset['safety']= label_encoder.fit_transform(dataset['safety'])
dataset['class']= label_encoder.fit_transform(dataset['class']) 
dataset

buying  maint  door  persons  lug_boot  safety  class
0          3      3     0        0         2       1      2
1          3      3     0        0         2       2      2
2          3      3     0        0         2       0      2
3          3      3     0        0         1       1      2
4          3      3     0        0         1       2      2
...      ...    ...   ...      ...       ...     ...    ...
1723       1      1     3        2         1       2      1
1724       1      1     3        2         1       0      3
1725       1      1     3        2         0       1      2
1726       1      1     3        2         0       2      1
1727       1      1     3        2         0       0      3

[1728 rows x 7 columns]

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   int32
 1   maint     1728 non-null   int32
 2   door      1728 non-null   int32
 3   persons   1728 non-null   int32
 4   lug_boot  1728 non-null   int32
 5   safety    1728 non-null   int32
 6   class     1728 non-null   int32
dtypes: int32(7)
memory usage: 47.4 KB


# Split

In [12]:
x = dataset.iloc[:,: len(dataset.columns)-1]
y = dataset.iloc[:,-1]

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.3)

In [14]:
x_train, y_train

(      buying  maint  door  persons  lug_boot  safety
 1317       1      3     0        2         1       1
 1500       1      0     3        1         0       1
 955        2      3     3        1         2       2
 916        2      3     1        2         0       2
 1220       2      1     1        0         1       0
 ...      ...    ...   ...      ...       ...     ...
 532        0      3     3        2         2       2
 36         3      3     1        1         2       1
 686        0      2     1        1         2       0
 651        0      2     0        0         1       1
 953        2      3     3        0         0       0
 
 [1209 rows x 6 columns],
 1317    2
 1500    2
 955     2
 916     0
 1220    2
        ..
 532     2
 36      2
 686     0
 651     2
 953     2
 Name: class, Length: 1209, dtype: int32)

# Training

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knnclassifier = KNeighborsClassifier(n_neighbors=5)

In [18]:
knnclassifier.fit(x_train, y_train)

KNeighborsClassifier()

In [19]:
acc = knnclassifier.score(x_test, y_test)
print(acc)

0.8747591522157996


In [29]:
import numpy as np
x_test = np.array(x_test)
y_test = np.array(y_test)

In [30]:
prediction = knnclassifier.predict(x_test)

In [70]:
for i in range(len(prediction)):
    print(f"{x_test[i]} ----> {y_test[i]} ----> {prediction[i]} = {y_test[i] == prediction[i]}")
#     n = knnclassifier.kneighbors([x_test[i]], 9, True)
#     print(n)

[1 2 0 1 2 2] ----> 0 ----> 2 = False
[3 2 0 0 1 1] ----> 2 ----> 2 = True
[1 0 1 0 2 1] ----> 2 ----> 2 = True
[2 1 3 1 2 2] ----> 0 ----> 2 = False
[3 0 1 1 0 0] ----> 2 ----> 0 = False
[3 1 1 2 2 1] ----> 2 ----> 2 = True
[1 2 1 2 2 0] ----> 1 ----> 0 = False
[2 3 3 0 2 2] ----> 2 ----> 2 = True
[0 1 2 2 1 0] ----> 0 ----> 0 = True
[3 3 2 2 1 0] ----> 2 ----> 2 = True
[0 0 0 1 1 2] ----> 2 ----> 2 = True
[1 0 1 2 0 2] ----> 0 ----> 0 = True
[3 0 0 2 2 1] ----> 2 ----> 2 = True
[2 2 1 2 0 0] ----> 3 ----> 3 = True
[3 0 2 1 0 2] ----> 2 ----> 2 = True
[3 0 2 2 2 2] ----> 2 ----> 2 = True
[0 3 0 1 0 2] ----> 2 ----> 2 = True
[2 0 3 2 2 0] ----> 0 ----> 0 = True
[1 1 2 2 2 2] ----> 0 ----> 0 = True
[1 3 2 0 2 2] ----> 2 ----> 2 = True
[0 3 1 1 0 2] ----> 2 ----> 2 = True
[1 3 1 0 2 1] ----> 2 ----> 2 = True
[1 1 0 1 1 0] ----> 1 ----> 0 = False
[1 3 3 1 1 2] ----> 0 ----> 2 = False
[2 3 1 2 1 0] ----> 0 ----> 0 = True
[1 0 1 2 0 1] ----> 2 ----> 2 = True
[0 2 3 0 2 1] ----> 2 ----> 2 = 